# Generated by Django 2.2.4 on 2020-05-15 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TV_shows_app', '0002_auto_20200515_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='bound_network',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
